AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: test flight status
Resources:
  FlightStatus:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: test flight status
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::668454320451:role/lambda_basic_execution'
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
